import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { mkdir, readFile, rename, rm, symlink, writeFile } from "node:fs/promises";
import test from "node:test";
import { GM_CAPABILITY_CONTRACTS, PUBLIC_GM_CAPABILITIES } from "../dist/index.js";
import { safeChildEnvironment } from "../dist/processes/index.js";
import { canonicalHash, canonicalJson } from "../dist/transactions/canonical.js";
import { planHash } from "../dist/planning/index.js";
import { base, join, sandbox, setupPlan, REMOVAL_RETRIES } from "./helpers.js";

function git(cwd, args) { const nullDevice = process.platform === "win32" ? "NUL" : "/dev/null"; return execFileSync("git", ["--no-optional-locks", "-c", `core.hooksPath=${nullDevice}`, "-c", "commit.gpgsign=false", "-C", cwd, ...args], { encoding: "utf8", env: { ...safeChildEnvironment(), GIT_CONFIG_GLOBAL: nullDevice, GIT_CONFIG_NOSYSTEM: "1", GIT_CONFIG_SYSTEM: nullDevice, GIT_OPTIONAL_LOCKS: "0", GIT_TERMINAL_PROMPT: "0" }, stdio: ["ignore", "pipe", "ignore"], windowsHide: true }).trim(); }
function initRepository(project) { git(project, ["init", "--quiet"]); git(project, ["config", "user.name", "DevLab Test"]); git(project, ["config", "user.email", "devlab@example.invalid"]); git(project, ["add", "."]); git(project, ["commit", "--quiet", "-m", "project"]); return git(project, ["rev-parse", "HEAD"]); }

test("PUBLIC CONTRACT: exposes exactly six versioned capabilities", () => { assert.deepEqual(PUBLIC_GM_CAPABILITIES, ["GM_STATUS_V1", "GM_INSPECT_V1", "GM_PLAN_V1", "GM_APPLY_SAFE_V1", "GM_VERIFY_V1", "GM_ROLLBACK_V1"]); assert.deepEqual(GM_CAPABILITY_CONTRACTS.map(({ id }) => id), PUBLIC_GM_CAPABILITIES); });
test("PUBLIC BARREL: does not export transaction, process, path or verification primitives", async () => { const api = await import("../dist/index.js"); for (const internal of ["applyTransaction", "rollbackTransaction", "verifyProject", "createPlan", "inspectProject", "listTransactions", "runOwnedCommand", "ProcessLedger", "safeRelativePath", "canonicalBytes"]) assert.equal(internal in api, false); assert.equal(typeof api.GovernedGameMakerIdeAdapter, "function"); });
test("CAPABILITY METADATA: every public operation declares governed effects", () => { for (const capability of GM_CAPABILITY_CONTRACTS) { for (const field of ["inputSchema", "outputSchema", "authorizedRoots", "determinism", "timeout", "reversibility", "gate"]) assert.equal(typeof capability[field], "string"); assert.ok(capability.effects.length); assert.ok(capability.evidence.length); assert.ok(capability.errors.length >= 7); } });
test("ACTION GATE: all six levels are represented by contract vocabulary", () => { const gates = new Set(["READ_ONLY", "PLAN_ONLY", "SAFE_WRITE", "COMPILE", "RUN", "DESTRUCTIVE"]); for (const capability of GM_CAPABILITY_CONTRACTS) assert.ok(gates.has(capability.gate)); });
test("CANONICAL JSON: key order is stable and timestamps are not injected", () => { assert.equal(canonicalJson({ z: 1, a: [2, { b: true, a: false }] }), '{"a":[2,{"a":false,"b":true}],"z":1}'); assert.equal(canonicalHash({ a: 1 }), canonicalHash({ a: 1 })); });
test("INSPECT: snapshot is sorted, relative, timestamp-free and self-hashed", async () => { const box = await sandbox(); try { const { snapshot } = await setupPlan(box); const byteSort = (a, b) => Buffer.compare(Buffer.from(a), Buffer.from(b)); assert.equal(snapshot.projectType, "GameMaker"); assert.deepEqual(snapshot.files.map(({ path }) => path), [...snapshot.files.map(({ path }) => path)].sort(byteSort)); assert.ok(snapshot.files.every(({ path }) => !/^[A-Za-z]:/.test(path))); assert.equal(JSON.stringify(snapshot).includes("generatedAt"), false); assert.match(snapshot.fingerprint, /^[0-9a-f]{64}$/); assert.match(snapshot.snapshotHash, /^[0-9a-f]{64}$/); } finally { await box.cleanup(); } });
test("INSPECT: enumerates object, room and references", async () => { const box = await sandbox(); try { const { snapshot } = await setupPlan(box); assert.deepEqual(snapshot.objects, ["objects/obj_gm_bridge_pilot/obj_gm_bridge_pilot.yy"]); assert.deepEqual(snapshot.rooms, ["rooms/rm_gm_bridge_pilot/rm_gm_bridge_pilot.yy"]); assert.equal(snapshot.scripts.length, 0); assert.equal(snapshot.references.length, 2); } finally { await box.cleanup(); } });
test("INSPECT: project metadata bytes remain bound to the file inventory", async () => { const box = await sandbox(); const projectFile = join(box.root, box.projectRoot, "HermesBridgePilot.yyp"); try { const original = await readFile(projectFile); const changed = Buffer.from(original); changed[0] = changed[0] === 0x7b ? 0x5b : 0x7b; const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); const adapter = new GovernedGameMakerIdeAdapter(box.root, async () => []); await assert.rejects(() => adapter.inspect({ ...base(box.projectRoot, "metadata-race", "GM_INSPECT_V1"), afterWalk: async () => { await writeFile(projectFile, changed); } }), (error) => error.code === "CONCURRENT_MODIFICATION"); } finally { await box.cleanup(); } });
test("INSPECT: invalid UTF-8 project metadata is refused", async () => { const box = await sandbox(); const projectFile = join(box.root, box.projectRoot, "HermesBridgePilot.yyp"); try { const bytes = await readFile(projectFile); const marker = bytes.indexOf(Buffer.from("2026.0.0.16")); assert.notEqual(marker, -1); bytes[marker] = 0xff; await writeFile(projectFile, bytes); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "metadata-utf8", "GM_INSPECT_V1")), (error) => error.code === "INVALID_REQUEST"); } finally { await box.cleanup(); } });
test("INSPECT: a UTF-8 BOM is hashed as bytes but ignored when parsing JSON", async () => { const box = await sandbox(); const projectFile = join(box.root, box.projectRoot, "HermesBridgePilot.yyp"); try { const bytes = await readFile(projectFile); await writeFile(projectFile, Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), bytes])); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); const snapshot = await new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "metadata-bom", "GM_INSPECT_V1")); const projectEntry = snapshot.files.find(({ path }) => path === "HermesBridgePilot.yyp"); assert.equal(projectEntry?.size, bytes.length + 3); assert.equal(snapshot.projectType, "GameMaker"); } finally { await box.cleanup(); } });
test("INSPECT GIT: hostile GIT_DIR and GIT_WORK_TREE cannot replace the inspected repository", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); const foreign = join(box.root, "Foreign"); const previousGitDir = process.env.GIT_DIR; const previousWorkTree = process.env.GIT_WORK_TREE; const previousGlobalConfig = process.env.GIT_CONFIG_GLOBAL; try { git(project, ["init", "--quiet"]); git(project, ["config", "user.name", "DevLab Test"]); git(project, ["config", "user.email", "devlab@example.invalid"]); git(project, ["add", "."]); git(project, ["commit", "--quiet", "-m", "project"]); const projectHead = git(project, ["rev-parse", "HEAD"]); git(box.root, ["init", "--quiet", foreign]); git(foreign, ["config", "user.name", "DevLab Test"]); git(foreign, ["config", "user.email", "devlab@example.invalid"]); await writeFile(join(foreign, "foreign.txt"), "foreign repository\n", "utf8"); git(foreign, ["add", "."]); git(foreign, ["commit", "--quiet", "-m", "foreign"]); const foreignHead = git(foreign, ["rev-parse", "HEAD"]); assert.notEqual(projectHead, foreignHead); process.env.GIT_DIR = join(foreign, ".git"); process.env.GIT_WORK_TREE = foreign; process.env.GIT_CONFIG_GLOBAL = join(foreign, "host-global-config"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); const adapter = new GovernedGameMakerIdeAdapter(box.root, async () => []); const snapshot = await adapter.inspect(base(box.projectRoot, "git-env-isolation", "GM_INSPECT_V1")); assert.equal(snapshot.gitHead, projectHead); assert.deepEqual(snapshot.gitStatus, []); } finally { if (previousGitDir === undefined) delete process.env.GIT_DIR; else process.env.GIT_DIR = previousGitDir; if (previousWorkTree === undefined) delete process.env.GIT_WORK_TREE; else process.env.GIT_WORK_TREE = previousWorkTree; if (previousGlobalConfig === undefined) delete process.env.GIT_CONFIG_GLOBAL; else process.env.GIT_CONFIG_GLOBAL = previousGlobalConfig; await box.cleanup(); } });
test("INSPECT GIT: hostile PATH cannot replace the absolute Git executable", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); const previousPath = process.env.PATH; try { const head = initRepository(project); process.env.PATH = join(box.root, "hostile-path-without-git"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); const snapshot = await new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-path-isolation", "GM_INSPECT_V1")); assert.equal(snapshot.gitHead, head); assert.deepEqual(snapshot.gitStatus, []); } finally { if (previousPath === undefined) delete process.env.PATH; else process.env.PATH = previousPath; await box.cleanup(); } });
test("INSPECT GIT: command-line worktree containment overrides hostile local core.worktree", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); const foreign = join(box.root, "ForeignWorkTree"); try { await mkdir(foreign); const head = initRepository(project); git(project, ["config", "core.worktree", foreign]); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); const snapshot = await new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-local-worktree", "GM_INSPECT_V1")); assert.equal(snapshot.gitHead, head); assert.deepEqual(snapshot.gitStatus, []); } finally { await box.cleanup(); } });
test("INSPECT GIT: external gitfile metadata is rejected", async () => { const box = await sandbox(); const foreignBox = await sandbox("Foreign"); const project = join(box.root, box.projectRoot); const foreign = join(foreignBox.root, foreignBox.projectRoot); try { initRepository(project); initRepository(foreign); await rm(join(project, ".git"), REMOVAL_RETRIES); await writeFile(join(project, ".git"), `gitdir: ${join(foreign, ".git")}\n`, "utf8"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "gitfile-escape", "GM_INSPECT_V1")), (error) => error.code === "PATH_ESCAPE"); } finally { await box.cleanup(); await foreignBox.cleanup(); } });
test("INSPECT GIT: local config includes are rejected before repository inspection", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); try { initRepository(project); const externalConfig = join(box.root, "foreign.gitconfig"); await writeFile(externalConfig, "[core]\n\tworktree = ../Foreign\n", "utf8"); git(project, ["config", "include.path", externalConfig]); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-include", "GM_INSPECT_V1")), (error) => error.code === "PATH_ESCAPE"); } finally { await box.cleanup(); } });
test("INSPECT GIT: external common directories are rejected before Git runs", async () => { const box = await sandbox(); const foreignBox = await sandbox("Foreign"); const project = join(box.root, box.projectRoot); const foreign = join(foreignBox.root, foreignBox.projectRoot); try { initRepository(project); initRepository(foreign); await writeFile(join(project, ".git", "commondir"), join(foreign, ".git"), "utf8"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-common-escape", "GM_INSPECT_V1")), (error) => error.code === "PATH_ESCAPE"); } finally { await box.cleanup(); await foreignBox.cleanup(); } });
test("INSPECT GIT: alternate object databases are rejected", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); try { initRepository(project); const alternate = join(box.root, "AlternateObjects"); await mkdir(alternate); const info = join(project, ".git", "objects", "info"); await mkdir(info, { recursive: true }); await writeFile(join(info, "alternates"), `${alternate}\n`, "utf8"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-alternates", "GM_INSPECT_V1")), (error) => error.code === "PATH_ESCAPE"); } finally { await box.cleanup(); } });
test("INSPECT GIT: object database junctions are rejected", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); try { initRepository(project); const foreignObjects = join(box.root, "ForeignObjects"); await mkdir(foreignObjects); await rm(join(project, ".git", "objects"), REMOVAL_RETRIES); await symlink(foreignObjects, join(project, ".git", "objects"), process.platform === "win32" ? "junction" : "dir"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-objects-link", "GM_INSPECT_V1")), (error) => error.code === "PATH_ESCAPE"); } finally { await box.cleanup(); } });
test("INSPECT GIT: a nested object pack junction escaping projectsDir is rejected", async () => { const box = await sandbox(); const foreignBox = await sandbox("ForeignPack"); const project = join(box.root, box.projectRoot); const pack = join(project, ".git", "objects", "pack"); const foreignPack = join(foreignBox.root, "pack"); try { initRepository(project); await rename(pack, foreignPack); await symlink(foreignPack, pack, process.platform === "win32" ? "junction" : "dir"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-pack-link", "GM_INSPECT_V1")), (error) => error.code === "PATH_ESCAPE"); } finally { await box.cleanup(); await foreignBox.cleanup(); } });
for (const key of ["filter.devlab.clean", "filter.devlab.smudge", "filter.devlab.process", "diff.devlab.command", "diff.devlab.textconv", "core.attributesFile"]) test(`INSPECT GIT: dangerous local config ${key} is rejected before status`, async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); try { initRepository(project); git(project, ["config", key, "devlab-command-must-not-run"]); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, `git-dangerous-${key.replace(/[^a-z]+/gi, "-")}`, "GM_INSPECT_V1")), (error) => error.code === "GATE_VIOLATION"); } finally { await box.cleanup(); } });
test("INSPECT GIT: dangerous worktree config is rejected before its filter can run", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); const sentinel = join(box.root, "worktree-filter-ran.txt"); try { initRepository(project); await writeFile(join(project, ".gitattributes"), "filter-target.txt filter=devlab\n", "utf8"); await writeFile(join(project, "filter-target.txt"), "baseline\n", "utf8"); git(project, ["add", ".gitattributes", "filter-target.txt"]); git(project, ["commit", "--quiet", "-m", "filter fixture"]); git(project, ["config", "extensions.worktreeConfig", "true"]); const command = `node -e \"require('fs').writeFileSync(process.argv[1],'ran')\" \"${sentinel.replace(/\\/g, "/")}\"`; git(project, ["config", "--worktree", "filter.devlab.clean", command]); await writeFile(join(project, "filter-target.txt"), "changed\n", "utf8"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-worktree-filter", "GM_INSPECT_V1")), (error) => error.code === "GATE_VIOLATION"); assert.equal(await readFile(sentinel).catch(() => null), null); } finally { await box.cleanup(); } });
test("INSPECT GIT: status failure is fail-closed instead of clean", async () => { const box = await sandbox(); const project = join(box.root, box.projectRoot); try { initRepository(project); await writeFile(join(project, ".git", "index"), "not a git index\n", "utf8"); const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); await assert.rejects(() => new GovernedGameMakerIdeAdapter(box.root, async () => []).inspect(base(box.projectRoot, "git-status-failure", "GM_INSPECT_V1")), (error) => error.code === "GATE_VIOLATION"); } finally { await box.cleanup(); } });
test("STATUS: ready fixture is read without current-working-directory fallback", async () => { const box = await sandbox(); try { const { adapter, snapshot } = await setupPlan(box); const result = await adapter.status({ ...base(box.projectRoot, "status-1", "GM_STATUS_V1"), expectedProjectFingerprint: snapshot.fingerprint }); assert.equal(result.state, "READY"); assert.equal(result.projectRoot, box.projectRoot); } finally { await box.cleanup(); } });
test("PLAN: is frozen, cryptographically stable and bound to snapshot/project/content", async () => { const box = await sandbox(); try { const { plan, planHash: digest } = await setupPlan(box); assert.ok(Object.isFrozen(plan)); assert.ok(Object.isFrozen(plan.files)); assert.ok(Object.isFrozen(plan.allowedExtensions)); assert.deepEqual(plan.allowedExtensions, ["gml", "json", "yy", "yyp"]); assert.equal(digest, planHash(plan)); assert.match(digest, /^[0-9a-f]{64}$/); assert.match(plan.files[0].afterSha256, /^[0-9a-f]{64}$/); assert.equal(plan.projectRoot, box.projectRoot); } finally { await box.cleanup(); } });
test("PLAN: changing transaction binding changes plan hash", async () => { const a = await sandbox("A"); const b = await sandbox("B"); try { const p1 = await setupPlan(a, "tx-a"); const p2 = await setupPlan(b, "tx-b"); assert.notEqual(p1.planHash, p2.planHash); } finally { await a.cleanup(); await b.cleanup(); } });
test("PLAN DETERMINISM: volatile process inventory does not change snapshot or plan hash", async () => { const box = await sandbox(); try { let running = false; const inventory = async () => running ? [{ pid: 99, parentPid: 1, name: "Igor.exe", executable: "C:\\Igor.exe", commandLine: "Igor", creationDate: "volatile" }] : []; const { GovernedGameMakerIdeAdapter } = await import("../dist/index.js"); const adapter = new GovernedGameMakerIdeAdapter(box.root, inventory); const first = await setupPlan(box, "stable-process", 2, adapter); running = true; const second = await setupPlan(box, "stable-process", 2, adapter); assert.equal(first.snapshot.snapshotHash, second.snapshot.snapshotHash); assert.equal(first.planHash, second.planHash); } finally { await box.cleanup(); } });
test("PLAN_ONLY: emits no evidence or project mutation", async () => { const box = await sandbox(); try { const { current } = await setupPlan(box); const { readFile, join } = await import("./helpers.js"); assert.equal(await readFile(join(box.root, box.projectRoot, "objects/obj_gm_bridge_pilot/Create_0.gml"), "utf8"), current); const { stat } = await import("node:fs/promises"); assert.equal(await stat(join(box.root, ".gm-bridge-evidence")).catch(() => null), null); } finally { await box.cleanup(); } });
test("REQUEST CONTRACT: wrong capability cannot inspect", async () => { const box = await sandbox(); try { const { adapter } = await setupPlan(box); await assert.rejects(() => adapter.inspect(base(box.projectRoot, "bad-cap", "GM_ROLLBACK_V1")), (error) => error.code === "GATE_VIOLATION"); } finally { await box.cleanup(); } });
