import assert from "node:assert/strict";
import test from "node:test";
import { GM_CAPABILITY_CONTRACTS, PUBLIC_GM_CAPABILITIES, canonicalHash, canonicalJson, planHash } from "../dist/index.js";
import { base, sandbox, setupPlan } from "./helpers.js";

test("PUBLIC CONTRACT: exposes exactly six versioned capabilities", () => { assert.deepEqual(PUBLIC_GM_CAPABILITIES, ["GM_STATUS_V1", "GM_INSPECT_V1", "GM_PLAN_V1", "GM_APPLY_SAFE_V1", "GM_VERIFY_V1", "GM_ROLLBACK_V1"]); assert.deepEqual(GM_CAPABILITY_CONTRACTS.map(({ id }) => id), PUBLIC_GM_CAPABILITIES); });
test("CAPABILITY METADATA: every public operation declares governed effects", () => { for (const capability of GM_CAPABILITY_CONTRACTS) { for (const field of ["inputSchema", "outputSchema", "authorizedRoots", "determinism", "timeout", "reversibility", "gate"]) assert.equal(typeof capability[field], "string"); assert.ok(capability.effects.length); assert.ok(capability.evidence.length); assert.ok(capability.errors.length >= 7); } });
test("ACTION GATE: all six levels are represented by contract vocabulary", () => { const gates = new Set(["READ_ONLY", "PLAN_ONLY", "SAFE_WRITE", "COMPILE", "RUN", "DESTRUCTIVE"]); for (const capability of GM_CAPABILITY_CONTRACTS) assert.ok(gates.has(capability.gate)); });
test("CANONICAL JSON: key order is stable and timestamps are not injected", () => { assert.equal(canonicalJson({ z: 1, a: [2, { b: true, a: false }] }), '{"a":[2,{"a":false,"b":true}],"z":1}'); assert.equal(canonicalHash({ a: 1 }), canonicalHash({ a: 1 })); });
test("INSPECT: snapshot is sorted, relative, timestamp-free and self-hashed", async () => { const box = await sandbox(); try { const { snapshot } = await setupPlan(box); assert.equal(snapshot.projectType, "GameMaker"); assert.deepEqual(snapshot.files.map(({ path }) => path), [...snapshot.files.map(({ path }) => path)].sort((a, b) => a.localeCompare(b))); assert.ok(snapshot.files.every(({ path }) => !/^[A-Za-z]:/.test(path))); assert.equal(JSON.stringify(snapshot).includes("generatedAt"), false); assert.match(snapshot.fingerprint, /^[0-9a-f]{64}$/); assert.match(snapshot.snapshotHash, /^[0-9a-f]{64}$/); } finally { await box.cleanup(); } });
test("INSPECT: enumerates object, room and references", async () => { const box = await sandbox(); try { const { snapshot } = await setupPlan(box); assert.deepEqual(snapshot.objects, ["objects/obj_gm_bridge_pilot/obj_gm_bridge_pilot.yy"]); assert.deepEqual(snapshot.rooms, ["rooms/rm_gm_bridge_pilot/rm_gm_bridge_pilot.yy"]); assert.equal(snapshot.scripts.length, 0); assert.equal(snapshot.references.length, 2); } finally { await box.cleanup(); } });
test("STATUS: ready fixture is read without current-working-directory fallback", async () => { const box = await sandbox(); try { const { adapter, snapshot } = await setupPlan(box); const result = await adapter.status({ ...base(box.projectRoot, "status-1", "GM_STATUS_V1"), expectedProjectFingerprint: snapshot.fingerprint }); assert.equal(result.state, "READY"); assert.equal(result.projectRoot, box.projectRoot); } finally { await box.cleanup(); } });
test("PLAN: is frozen, cryptographically stable and bound to snapshot/project/content", async () => { const box = await sandbox(); try { const { plan, planHash: digest } = await setupPlan(box); assert.ok(Object.isFrozen(plan)); assert.ok(Object.isFrozen(plan.files)); assert.equal(digest, planHash(plan)); assert.match(digest, /^[0-9a-f]{64}$/); assert.match(plan.files[0].afterSha256, /^[0-9a-f]{64}$/); assert.equal(plan.projectRoot, box.projectRoot); } finally { await box.cleanup(); } });
test("PLAN: changing transaction binding changes plan hash", async () => { const a = await sandbox("A"); const b = await sandbox("B"); try { const p1 = await setupPlan(a, "tx-a"); const p2 = await setupPlan(b, "tx-b"); assert.notEqual(p1.planHash, p2.planHash); } finally { await a.cleanup(); await b.cleanup(); } });
test("PLAN_ONLY: emits no evidence or project mutation", async () => { const box = await sandbox(); try { const { current } = await setupPlan(box); const { readFile, join } = await import("./helpers.js"); assert.equal(await readFile(join(box.root, box.projectRoot, "objects/obj_gm_bridge_pilot/Create_0.gml"), "utf8"), current); const { stat } = await import("node:fs/promises"); assert.equal(await stat(join(box.root, ".gm-bridge-evidence")).catch(() => null), null); } finally { await box.cleanup(); } });
test("REQUEST CONTRACT: wrong capability cannot inspect", async () => { const box = await sandbox(); try { const { adapter } = await setupPlan(box); await assert.rejects(() => adapter.inspect(base(box.projectRoot, "bad-cap", "GM_ROLLBACK_V1")), (error) => error.code === "GATE_VIOLATION"); } finally { await box.cleanup(); } });
