import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import test from "node:test";
import { base, join, sandbox, setupPlan, applyPlanned, targetFile } from "./helpers.js";

test("DRY RUN: defaults on and never creates transaction evidence", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "dry-default"); const result = await ctx.adapter.applySafe({ ...base(box.projectRoot, "dry-default", "GM_APPLY_SAFE_V1"), expectedProjectFingerprint: ctx.snapshot.fingerprint, plan: ctx.plan, planHash: ctx.planHash, confirm: true }); assert.equal(result.state, "DRY_RUN"); assert.equal(result.applied, false); assert.equal(await readFile(join(box.root, box.projectRoot, targetFile), "utf8"), ctx.current); } finally { await box.cleanup(); } });
test("SAFE WRITE: promotes only the allowlisted file and preserves backup", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "apply-1"); const result = await applyPlanned(ctx); assert.equal(result.state, "APPLIED"); assert.deepEqual(result.changedFiles, [targetFile]); assert.equal(await readFile(join(box.root, box.projectRoot, targetFile), "utf8"), ctx.content); assert.match(result.manifestSha256, /^[0-9a-f]{64}$/); } finally { await box.cleanup(); } });
test("ROLLBACK: restores STATE-A byte-exactly", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "rollback-1"); const applied = await applyPlanned(ctx); const result = await ctx.adapter.rollback({ ...base(box.projectRoot, "rollback-1", "GM_ROLLBACK_V1"), expectedProjectFingerprint: applied.projectFingerprint, planHash: ctx.planHash, confirm: true }); assert.equal(result.byteExact, true); assert.equal(result.projectFingerprint, ctx.snapshot.fingerprint); assert.equal(await readFile(join(box.root, box.projectRoot, targetFile), "utf8"), ctx.current); } finally { await box.cleanup(); } });
test("ROLLBACK: verifies original file set and sizes through fingerprint", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "rollback-files"); const before = ctx.snapshot.files.map(({ path, size }) => [path, size]); const applied = await applyPlanned(ctx); await ctx.adapter.rollback({ ...base(box.projectRoot, "rollback-files", "GM_ROLLBACK_V1"), expectedProjectFingerprint: applied.projectFingerprint, planHash: ctx.planHash, confirm: true }); const after = await ctx.adapter.inspect(base(box.projectRoot, "inspect-after", "GM_INSPECT_V1")); assert.deepEqual(after.files.map(({ path, size }) => [path, size]), before); } finally { await box.cleanup(); } });
for (const faultAt of ["before-staging", "during-staging", "before-promotion", "after-first-replace"]) test(`ATOMICITY: ${faultAt} never presents partial success`, async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, `fault-${faultAt}`); await assert.rejects(() => applyPlanned(ctx, faultAt)); const after = await ctx.adapter.inspect(base(box.projectRoot, `inspect-${faultAt}`, "GM_INSPECT_V1")); assert.equal(after.fingerprint, ctx.snapshot.fingerprint); assert.equal(await readFile(join(box.root, box.projectRoot, targetFile), "utf8"), ctx.current); } finally { await box.cleanup(); } });
test("TOCTOU: file change between plan and apply blocks without writes", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "stale-file"); await writeFile(join(box.root, box.projectRoot, targetFile), `${ctx.current}\n// external\n`); await assert.rejects(() => applyPlanned(ctx), (error) => error.code === "EXPECTED_HASH_MISMATCH" || error.code === "PLAN_STALE"); assert.match(await readFile(join(box.root, box.projectRoot, targetFile), "utf8"), /external/); } finally { await box.cleanup(); } });
test("PLAN TAMPER: changed plan with original hash is blocked", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "tamper-plan"); const tampered = { ...ctx.plan, allowlist: [] }; await assert.rejects(() => ctx.adapter.applySafe({ ...base(box.projectRoot, "tamper-plan", "GM_APPLY_SAFE_V1"), expectedProjectFingerprint: ctx.snapshot.fingerprint, plan: tampered, planHash: ctx.planHash, confirm: true, dryRun: false }), (error) => error.code === "PLAN_STALE"); } finally { await box.cleanup(); } });
test("ALLOWLIST: apply request cannot shrink or alter plan authorization", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "allowlist-change"); await assert.rejects(() => ctx.adapter.applySafe({ ...base(box.projectRoot, "allowlist-change", "GM_APPLY_SAFE_V1"), allowlist: ["rooms/rm_gm_bridge_pilot/rm_gm_bridge_pilot.yy"], expectedProjectFingerprint: ctx.snapshot.fingerprint, plan: ctx.plan, planHash: ctx.planHash, confirm: true, dryRun: false }), (error) => error.code === "FILE_NOT_ALLOWLISTED"); } finally { await box.cleanup(); } });
test("GATE: SAFE_WRITE without confirm is rejected", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "no-confirm"); await assert.rejects(() => ctx.adapter.applySafe({ ...base(box.projectRoot, "no-confirm", "GM_APPLY_SAFE_V1"), expectedProjectFingerprint: ctx.snapshot.fingerprint, plan: ctx.plan, planHash: ctx.planHash, confirm: false, dryRun: false }), (error) => error.code === "GATE_VIOLATION"); } finally { await box.cleanup(); } });
test("ROLLBACK: external change after apply blocks and preserves that change", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "rollback-concurrent"); const applied = await applyPlanned(ctx); await writeFile(join(box.root, box.projectRoot, targetFile), `${ctx.content}\n// later external\n`); const current = await ctx.adapter.inspect(base(box.projectRoot, "current", "GM_INSPECT_V1")); await assert.rejects(() => ctx.adapter.rollback({ ...base(box.projectRoot, "rollback-concurrent", "GM_ROLLBACK_V1"), expectedProjectFingerprint: current.fingerprint, planHash: ctx.planHash, confirm: true }), (error) => error.code === "CONCURRENT_MODIFICATION"); assert.match(await readFile(join(box.root, box.projectRoot, targetFile), "utf8"), /later external/); } finally { await box.cleanup(); } });
test("ROLLBACK: altered manifest is rejected fail-closed", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "manifest-tamper"); const applied = await applyPlanned(ctx); const manifest = join(box.root, ".gm-bridge-evidence", "transactions", "manifest-tamper", "manifest.json"); await writeFile(manifest, `${await readFile(manifest, "utf8")} `); await assert.rejects(() => ctx.adapter.rollback({ ...base(box.projectRoot, "manifest-tamper", "GM_ROLLBACK_V1"), expectedProjectFingerprint: applied.projectFingerprint, planHash: ctx.planHash, confirm: true }), (error) => error.code === "ROLLBACK_UNAVAILABLE"); } finally { await box.cleanup(); } });
test("REAPPLY: same transaction id is rejected", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "reapply-id"); await applyPlanned(ctx); await assert.rejects(() => applyPlanned(ctx), (error) => error.code === "EXPECTED_HASH_MISMATCH" || error.code === "PLAN_STALE" || error.code === "MUTATION_ALREADY_APPLIED"); } finally { await box.cleanup(); } });
test("NO CHANGE: idempotent mutation returns changedFiles=[]", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "no-change", 1); const result = await applyPlanned(ctx); assert.equal(result.state, "NO_CHANGE"); assert.deepEqual(result.changedFiles, []); assert.equal(result.rollbackAvailable, false); } finally { await box.cleanup(); } });
test("CRASH RECOVERY: WRITE_AHEAD partial promotion is recoverable on the next rollback", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "write-ahead-recovery"); await assert.rejects(() => applyPlanned(ctx, "leave-write-ahead-after-first-replace"), (error) => error.code === "ATOMIC_PROMOTION_FAILED"); const partial = await ctx.adapter.inspect(base(box.projectRoot, "partial", "GM_INSPECT_V1")); assert.notEqual(partial.fingerprint, ctx.snapshot.fingerprint); const status = await ctx.adapter.status({ ...base(box.projectRoot, "status-recovery", "GM_STATUS_V1"), expectedProjectFingerprint: partial.fingerprint }); assert.equal(status.state, "TRANSACTION_PENDING"); const restored = await ctx.adapter.rollback({ ...base(box.projectRoot, "write-ahead-recovery", "GM_ROLLBACK_V1"), expectedProjectFingerprint: partial.fingerprint, planHash: ctx.planHash, confirm: true }); assert.equal(restored.byteExact, true); assert.equal(restored.projectFingerprint, ctx.snapshot.fingerprint); } finally { await box.cleanup(); } });
