import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import test from "node:test";
import { base, join, sandbox, setupPlan, applyPlanned, targetFile } from "./helpers.js";

test("TEXT VERIFY: applied state parses but is not mislabeled compile-valid", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "verify-text"); const applied = await applyPlanned(ctx); const result = await ctx.adapter.verify({ ...base(box.projectRoot, "verify-text", "GM_VERIFY_V1"), expectedProjectFingerprint: applied.projectFingerprint, plan: ctx.plan, planHash: ctx.planHash, levels: ["TEXT_VALID"] }); assert.equal(result.levels.TEXT_VALID.passed, true); assert.equal(result.levels.COMPILE_VALID, undefined); assert.equal(result.highestLevel, "TEXT_VALID"); } finally { await box.cleanup(); } });
test("VERIFY: missing applied transaction is MUTATION_NOT_FOUND", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "not-applied"); await assert.rejects(() => ctx.adapter.verify({ ...base(box.projectRoot, "not-applied", "GM_VERIFY_V1"), expectedProjectFingerprint: ctx.snapshot.fingerprint, plan: ctx.plan, planHash: ctx.planHash, levels: ["TEXT_VALID"] }), (error) => error.code === "MUTATION_NOT_FOUND"); } finally { await box.cleanup(); } });
test("VERIFY TOCTOU: post-apply file drift is rejected", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "verify-drift"); const applied = await applyPlanned(ctx); await writeFile(join(box.root, box.projectRoot, targetFile), `${ctx.content}\n// drift\n`); const current = await ctx.adapter.inspect(base(box.projectRoot, "drift-current", "GM_INSPECT_V1")); await assert.rejects(() => ctx.adapter.verify({ ...base(box.projectRoot, "verify-drift", "GM_VERIFY_V1"), expectedProjectFingerprint: current.fingerprint, plan: ctx.plan, planHash: ctx.planHash, levels: ["TEXT_VALID"] }), (error) => error.code === "CONCURRENT_MODIFICATION"); } finally { await box.cleanup(); } });
test("VERIFY POLICY: runtime forbidden cannot be silently elevated", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "runtime-forbidden"); const applied = await applyPlanned(ctx); await assert.rejects(() => ctx.adapter.verify({ ...base(box.projectRoot, "runtime-forbidden", "GM_VERIFY_V1"), verificationPolicy: { projectLoad: true, compile: true, runtime: "forbidden" }, expectedProjectFingerprint: applied.projectFingerprint, plan: ctx.plan, planHash: ctx.planHash, levels: ["RUNTIME_VALID"] }), (error) => error.code === "GATE_VIOLATION"); } finally { await box.cleanup(); } });
test("TEXT VERIFY NEGATIVE: structural invalidity reports FAIL, not compile PASS", async () => { const box = await sandbox(); try { const ctx = await setupPlan(box, "text-negative"); const applied = await applyPlanned(ctx); await writeFile(join(box.root, box.projectRoot, targetFile), "GM_BRIDGE_INTENTIONAL_SYNTAX_ERROR {"); const current = await ctx.adapter.inspect(base(box.projectRoot, "negative-current", "GM_INSPECT_V1")); const result = await ctx.adapter.verify({ ...base(box.projectRoot, "text-negative", "GM_VERIFY_V1"), expectedProjectFingerprint: current.fingerprint, levels: ["TEXT_VALID"] }); assert.equal(result.levels.TEXT_VALID.passed, false); assert.equal(result.rollbackRequired, true); assert.equal(result.compileExitCode, null); } finally { await box.cleanup(); } });
