import { constants } from "node:fs";
import { copyFile, mkdir, open, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";
import type { GmApplyResult, GmApplySafeRequest, GmMutationPlan, GmRollbackRequest, GmRollbackResult } from "../contracts/index.js";
import { GmAdapterError, fail } from "../errors/index.js";
import { inspectProject } from "../inspection/index.js";
import { resolveInsideRoot, safeRelativePath, safeTransactionId } from "../paths/index.js";
import type { ProcessInventory } from "../processes/index.js";
import { planHash as hashPlan } from "../planning/index.js";
import { canonicalBytes, canonicalHash, sha256 } from "./canonical.js";

interface TransactionFile { readonly path: string; readonly action: "modify" | "create"; readonly beforeSha256: string | null; readonly afterSha256: string; readonly backupPath: string | null; readonly stagingPath: string }
interface TransactionManifest { readonly schemaVersion: 1; readonly transactionId: string; readonly projectRoot: string; readonly operation: "apply-safe"; readonly gate: "SAFE_WRITE"; readonly capability: "GM_APPLY_SAFE_V1"; readonly expectedHead: string | null; readonly expectedProjectFingerprint: string; readonly planHash: string; readonly confirm: true; readonly state: "WRITE_AHEAD" | "APPLIED" | "FAILED" | "ROLLED_BACK"; readonly files: readonly TransactionFile[]; readonly verification: GmMutationPlan["verification"]; readonly rollback: Readonly<{ available: boolean; required: true }> }
interface Ledger { readonly schemaVersion: 1; readonly transactionId: string; readonly manifestSha256: string; readonly state: TransactionManifest["state"] }
const exists = async (path: string): Promise<boolean> => Boolean(await stat(path).catch(() => null));
async function atomicRename(source: string, destination: string): Promise<void> { let last: unknown; for (let attempt = 0; attempt < 3; attempt++) { try { await rename(source, destination); return; } catch (error) { last = error; await new Promise((resolve) => setTimeout(resolve, 20 * (attempt + 1))); } } throw last; }
async function writeCanonical(path: string, value: unknown): Promise<void> { await mkdir(dirname(path), { recursive: true }); const temporary = `${path}.next`; await writeFile(temporary, canonicalBytes(value), { flag: "wx" }); await atomicRename(temporary, path); }
async function acquireLock(lockPath: string, transactionId: string): Promise<() => Promise<void>> {
  await mkdir(dirname(lockPath), { recursive: true });
  try { const handle = await open(lockPath, constants.O_CREAT | constants.O_EXCL | constants.O_WRONLY, 0o600); await handle.writeFile(canonicalBytes({ schemaVersion: 1, pid: process.pid, transactionId })); await handle.close(); }
  catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; const stale = JSON.parse(await readFile(lockPath, "utf8")) as { pid?: number }; let alive = false; if (stale.pid) { try { process.kill(stale.pid, 0); alive = true; } catch {} } if (alive) fail("BUSY", "project transaction lock is active", true); await rm(lockPath); return acquireLock(lockPath, transactionId); }
  return async () => { const value = JSON.parse(await readFile(lockPath, "utf8")) as { transactionId?: string }; if (value.transactionId === transactionId) await rm(lockPath); };
}
async function transactionPaths(projectsDir: string, evidenceRoot: string, projectRoot: string, transactionId: string): Promise<Readonly<{ root: string; relativeRoot: string; staging: string; backups: string; manifest: string; ledger: string; lock: string }>> {
  const evidence = safeRelativePath(evidenceRoot, "evidenceRoot"); const root = await resolveInsideRoot(projectsDir, evidence); await mkdir(root, { recursive: true }); const tx = safeTransactionId(transactionId); const relativeRoot = `${evidence}/transactions/${tx}`; const transactionRoot = await resolveInsideRoot(projectsDir, relativeRoot); return Object.freeze({ root: transactionRoot, relativeRoot, staging: `${transactionRoot}/staging`, backups: `${transactionRoot}/backups`, manifest: `${transactionRoot}/manifest.json`, ledger: `${transactionRoot}/ledger.json`, lock: `${root}/locks/${sha256(Buffer.from(safeRelativePath(projectRoot)))}.lock` });
}
function assertPlan(request: GmApplySafeRequest | GmRollbackRequest, plan?: GmMutationPlan): asserts plan is GmMutationPlan { if (!plan || hashPlan(plan) !== request.planHash || plan.transactionId !== request.transactionId || plan.projectRoot !== request.projectRoot) fail("PLAN_STALE", "plan hash or binding is invalid", true); }
async function writeManifest(paths: Awaited<ReturnType<typeof transactionPaths>>, manifest: TransactionManifest): Promise<string> { await writeCanonical(paths.manifest, manifest); const digest = sha256(await readFile(paths.manifest)); await writeCanonical(paths.ledger, { schemaVersion: 1, transactionId: manifest.transactionId, manifestSha256: digest, state: manifest.state } satisfies Ledger); return digest; }
async function loadManifest(paths: Awaited<ReturnType<typeof transactionPaths>>): Promise<TransactionManifest> { if (!(await exists(paths.manifest)) || !(await exists(paths.ledger))) fail("MUTATION_NOT_FOUND", "transaction evidence is missing", true); const bytes = await readFile(paths.manifest); const ledger = JSON.parse(await readFile(paths.ledger, "utf8")) as Ledger; if (sha256(bytes) !== ledger.manifestSha256) fail("ROLLBACK_UNAVAILABLE", "transaction manifest was altered", false); return JSON.parse(bytes.toString("utf8")) as TransactionManifest; }

export async function applyTransaction(projectsDir: string, request: GmApplySafeRequest, inventory?: ProcessInventory): Promise<GmApplyResult> {
  if (request.capability !== "GM_APPLY_SAFE_V1") fail("GATE_VIOLATION", "applySafe requires GM_APPLY_SAFE_V1"); if (!request.confirm) fail("GATE_VIOLATION", "SAFE_WRITE requires confirm=true"); assertPlan(request, request.plan);
  const dryRun = request.dryRun !== false; const plan = request.plan; if (!request.expectedProjectFingerprint || request.expectedProjectFingerprint !== plan.projectFingerprint) fail("PLAN_STALE", "request fingerprint is not bound to plan", true);
  const projectRoot = safeRelativePath(request.projectRoot); const evidenceRoot = safeRelativePath(request.evidenceRoot); if (evidenceRoot === projectRoot || evidenceRoot.startsWith(`${projectRoot}/`)) fail("AUTHZ_PROJECT_ROOT", "evidenceRoot must be outside projectRoot");
  const snapshot = await inspectProject(projectsDir, { ...request, capability: "GM_INSPECT_V1" }, inventory); if (snapshot.snapshotHash !== plan.snapshotHash) fail("PLAN_STALE", "snapshot changed since plan", true);
  for (const file of plan.files) if (!plan.allowlist.includes(file.path) || !request.allowlist.map((path) => safeRelativePath(path)).includes(file.path)) fail("FILE_NOT_ALLOWLISTED", "apply allowlist differs from plan", false, { path: file.path });
  const planDigest = hashPlan(plan); if (dryRun) return Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, applied: false, dryRun: true, state: "DRY_RUN", planHash: planDigest, manifestPath: "", manifestSha256: canonicalHash({ planHash: planDigest, state: "DRY_RUN" }), changedFiles: Object.freeze([]), rollbackAvailable: false, projectFingerprint: snapshot.fingerprint });
  if (plan.files.every((file) => file.beforeSha256 === file.afterSha256)) return Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, applied: false, dryRun: false, state: "NO_CHANGE", planHash: planDigest, manifestPath: "", manifestSha256: canonicalHash({ planHash: planDigest, state: "NO_CHANGE" }), changedFiles: Object.freeze([]), rollbackAvailable: false, projectFingerprint: snapshot.fingerprint });
  if (snapshot.processes.some(({ name }) => /^GameMaker(?:\.exe)?$/i.test(name))) fail("GATE_VIOLATION", "SAFE_WRITE is blocked while GameMaker is open", true);
  if (request.faultAt === "before-staging") fail("ATOMIC_PROMOTION_FAILED", "injected pre-staging failure", true);
  const paths = await transactionPaths(projectsDir, evidenceRoot, projectRoot, request.transactionId); if (await exists(paths.root)) fail("MUTATION_ALREADY_APPLIED", "transaction directory already exists", true); const release = await acquireLock(paths.lock, request.transactionId); const root = await resolveInsideRoot(projectsDir, projectRoot, { existing: true }); let promoted = 0;
  const txFiles: TransactionFile[] = [];
  try {
    await mkdir(paths.staging, { recursive: true }); await mkdir(paths.backups, { recursive: true });
    for (const file of plan.files) {
      const destination = await resolveInsideRoot(root, file.path); const current = await readFile(destination).catch((error: NodeJS.ErrnoException) => error.code === "ENOENT" ? null : Promise.reject(error));
      if (sha256(current ?? Buffer.alloc(0)) !== (file.beforeSha256 ?? sha256(Buffer.alloc(0)))) fail("EXPECTED_HASH_MISMATCH", "target changed before staging", true, { path: file.path });
      const staged = `${paths.staging}/${file.path}`; await mkdir(dirname(staged), { recursive: true }); const after = Buffer.from(file.afterContentBase64, "base64"); await writeFile(staged, after, { flag: "wx" }); if (sha256(await readFile(staged)) !== file.afterSha256) fail("ATOMIC_PROMOTION_FAILED", "staged hash mismatch", false, { path: file.path });
      let backupPath: string | null = null; if (current) { backupPath = `backups/${file.path}.blob`; const backup = `${paths.root}/${backupPath}`; await mkdir(dirname(backup), { recursive: true }); await copyFile(destination, backup, constants.COPYFILE_EXCL); if (sha256(await readFile(backup)) !== file.beforeSha256) fail("ATOMIC_PROMOTION_FAILED", "backup hash mismatch", false, { path: file.path }); }
      txFiles.push(Object.freeze({ path: file.path, action: file.action, beforeSha256: file.beforeSha256, afterSha256: file.afterSha256, backupPath, stagingPath: `staging/${file.path}` })); if (request.faultAt === "during-staging") fail("ATOMIC_PROMOTION_FAILED", "injected staging failure", true);
    }
    let manifest: TransactionManifest = Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, projectRoot, operation: "apply-safe", gate: "SAFE_WRITE", capability: "GM_APPLY_SAFE_V1", expectedHead: plan.expectedHead, expectedProjectFingerprint: plan.projectFingerprint, planHash: planDigest, confirm: true, state: "WRITE_AHEAD", files: Object.freeze(txFiles), verification: plan.verification, rollback: Object.freeze({ available: true, required: true }) });
    await writeManifest(paths, manifest); if (request.faultAt === "before-promotion") fail("ATOMIC_PROMOTION_FAILED", "injected pre-promotion failure", true);
    for (const file of txFiles) { const destination = await resolveInsideRoot(root, file.path); await mkdir(dirname(destination), { recursive: true }); await atomicRename(`${paths.root}/${file.stagingPath}`, destination); promoted++; if (request.faultAt === "after-first-replace" && promoted === 1) fail("ATOMIC_PROMOTION_FAILED", "injected post-replace failure", true); }
    for (const file of txFiles) if (sha256(await readFile(await resolveInsideRoot(root, file.path))) !== file.afterSha256) fail("ATOMIC_PROMOTION_FAILED", "post-promotion hash mismatch", false, { path: file.path });
    manifest = Object.freeze({ ...manifest, state: "APPLIED" }); const manifestSha256 = await writeManifest(paths, manifest); const afterSnapshot = await inspectProject(projectsDir, { ...request, capability: "GM_INSPECT_V1", expectedProjectFingerprint: null }, inventory);
    return Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, applied: true, dryRun: false, state: "APPLIED", planHash: planDigest, manifestPath: `${paths.relativeRoot}/manifest.json`, manifestSha256, changedFiles: Object.freeze(txFiles.map(({ path }) => path)), rollbackAvailable: true, projectFingerprint: afterSnapshot.fingerprint });
  } catch (error) {
    if (promoted > 0) { for (const file of [...txFiles].reverse()) { const destination = await resolveInsideRoot(root, file.path); if (file.backupPath) { const rescue = `${paths.root}/failed/${file.path}`; await mkdir(dirname(rescue), { recursive: true }); if (await exists(destination)) await atomicRename(destination, rescue); await atomicRename(`${paths.root}/${file.backupPath}`, destination); } else if (await exists(destination)) { const rescue = `${paths.root}/failed/${file.path}`; await mkdir(dirname(rescue), { recursive: true }); await atomicRename(destination, rescue); } } }
    if (await exists(paths.root)) { const failed: TransactionManifest = Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, projectRoot, operation: "apply-safe", gate: "SAFE_WRITE", capability: "GM_APPLY_SAFE_V1", expectedHead: plan.expectedHead, expectedProjectFingerprint: plan.projectFingerprint, planHash: planDigest, confirm: true, state: "FAILED", files: Object.freeze(txFiles), verification: plan.verification, rollback: Object.freeze({ available: promoted > 0, required: true }) }); await writeManifest(paths, failed).catch(() => undefined); }
    throw error;
  } finally { await release(); }
}

export async function rollbackTransaction(projectsDir: string, request: GmRollbackRequest, inventory?: ProcessInventory): Promise<GmRollbackResult> {
  if (request.capability !== "GM_ROLLBACK_V1" || !request.confirm) fail("GATE_VIOLATION", "rollback requires GM_ROLLBACK_V1 and confirm=true"); const paths = await transactionPaths(projectsDir, request.evidenceRoot, request.projectRoot, request.transactionId); let manifest = await loadManifest(paths); if (manifest.planHash !== request.planHash || manifest.projectRoot !== request.projectRoot || manifest.state !== "APPLIED") fail("ROLLBACK_UNAVAILABLE", "transaction binding or state is invalid", false);
  const root = await resolveInsideRoot(projectsDir, request.projectRoot, { existing: true }); const current = await inspectProject(projectsDir, { ...request, capability: "GM_INSPECT_V1" }, inventory); if (request.expectedProjectFingerprint !== current.fingerprint) fail("CONCURRENT_MODIFICATION", "project changed before rollback", true);
  for (const file of manifest.files) { const destination = await resolveInsideRoot(root, file.path); const bytes = await readFile(destination).catch(() => null); if (!bytes || sha256(bytes) !== file.afterSha256) fail("CONCURRENT_MODIFICATION", "target changed after apply", true, { path: file.path }); if (file.backupPath && sha256(await readFile(`${paths.root}/${file.backupPath}`)) !== file.beforeSha256) fail("ROLLBACK_UNAVAILABLE", "backup blob is missing or corrupt", false, { path: file.path }); }
  const release = await acquireLock(paths.lock, request.transactionId); const restored: string[] = [];
  try { for (const file of [...manifest.files].reverse()) { const destination = await resolveInsideRoot(root, file.path); const applied = `${paths.root}/applied/${file.path}`; await mkdir(dirname(applied), { recursive: true }); await atomicRename(destination, applied); if (file.backupPath) await atomicRename(`${paths.root}/${file.backupPath}`, destination); restored.push(file.path); }
    for (const file of manifest.files) { if (file.beforeSha256 === null) { if (await exists(await resolveInsideRoot(root, file.path))) fail("ROLLBACK_INCOMPLETE", "created file remains after rollback"); } else if (sha256(await readFile(await resolveInsideRoot(root, file.path))) !== file.beforeSha256) fail("ROLLBACK_INCOMPLETE", "restored bytes do not match backup", false, { path: file.path }); }
    manifest = Object.freeze({ ...manifest, state: "ROLLED_BACK", rollback: Object.freeze({ available: false, required: true }) }); await writeManifest(paths, manifest); const snapshot = await inspectProject(projectsDir, { ...request, capability: "GM_INSPECT_V1", expectedProjectFingerprint: null }, inventory);
    return Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, restored: true, byteExact: snapshot.fingerprint === manifest.expectedProjectFingerprint, restoredFiles: Object.freeze(restored.sort()), projectFingerprint: snapshot.fingerprint, manifestPath: `${paths.relativeRoot}/manifest.json` });
  } finally { await release(); }
}

export async function listTransactions(projectsDir: string, evidenceRoot: string): Promise<Readonly<{ pending: readonly string[]; rollback: readonly string[] }>> {
  const root = await resolveInsideRoot(projectsDir, safeRelativePath(evidenceRoot)); const transactions = `${root}/transactions`; if (!(await exists(transactions))) return Object.freeze({ pending: Object.freeze([]), rollback: Object.freeze([]) });
  const { readdir } = await import("node:fs/promises"); const ids = (await readdir(transactions)).sort(); const pending: string[] = []; const rollback: string[] = [];
  for (const id of ids) { const manifest = await readFile(`${transactions}/${id}/manifest.json`, "utf8").then((text) => JSON.parse(text) as TransactionManifest).catch(() => null); if (!manifest || manifest.state === "WRITE_AHEAD" || manifest.state === "FAILED") pending.push(id); if (manifest?.state === "APPLIED") rollback.push(id); }
  return Object.freeze({ pending: Object.freeze(pending), rollback: Object.freeze(rollback) });
}
