import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { basename, dirname, isAbsolute } from "node:path";
import type { GmVerifyRequest, GmVerificationResult, VerificationLevel, VerificationOutcome } from "../contracts/index.js";
import { GmAdapterError, fail } from "../errors/index.js";
import { inspectProject, parseGameMakerJson } from "../inspection/index.js";
import { resolveInsideRoot, safeRelativePath } from "../paths/index.js";
import { ProcessLedger, commandHash, runOwnedCommand, windowsProcessInventory } from "../processes/index.js";
import { planHash } from "../planning/index.js";
import { canonicalBytes, sha256 } from "../transactions/canonical.js";

const passed = (evidence: string, detail: string): VerificationOutcome => Object.freeze({ passed: true, evidence, detail });
const failed = (evidence: string, detail: string): VerificationOutcome => Object.freeze({ passed: false, evidence, detail });
function validateGml(text: string): void {
  if (text.includes("GM_BRIDGE_INTENTIONAL_SYNTAX_ERROR")) fail("VERIFICATION_FAILED", "intentional invalid GML marker detected", true);
  let braces = 0; let quote: string | null = null; let escaped = false; for (const char of text) { if (quote) { if (escaped) escaped = false; else if (char === "\\") escaped = true; else if (char === quote) quote = null; } else if (char === "\"" || char === "'") quote = char; else if (char === "{") braces++; else if (char === "}" && --braces < 0) fail("VERIFICATION_FAILED", "GML braces are unbalanced", true); } if (quote || braces !== 0) fail("VERIFICATION_FAILED", "GML text is structurally incomplete", true);
}
async function textVerification(root: string): Promise<void> { const visit = async (directory: string): Promise<void> => { const { readdir } = await import("node:fs/promises"); for (const entry of await readdir(directory, { withFileTypes: true })) { if (entry.name === ".git") continue; const path = `${directory}/${entry.name}`; if (entry.isDirectory()) await visit(path); else if (/\.(?:yy|yyp|json)$/i.test(entry.name)) parseGameMakerJson(await readFile(path, "utf8")); else if (/\.gml$/i.test(entry.name)) validateGml(await readFile(path, "utf8")); } }; await visit(root); }
function ensureToolchain(input: NonNullable<GmVerifyRequest["igor"]>): void { for (const [field, value] of [["executable", input.executable], ["runtimePath", input.runtimePath], ["userDirectory", input.userDirectory], ["projectTool", input.projectTool]] as const) if (!isAbsolute(value)) fail("INVALID_REQUEST", `Igor ${field} must be explicit and absolute`); if (!/^Igor\.exe$/i.test(basename(input.executable))) fail("INVALID_REQUEST", "configured compiler is not Igor.exe"); if (!/^ProjectTool\.exe$/i.test(basename(input.projectTool))) fail("INVALID_REQUEST", "configured project tool is not ProjectTool.exe"); }

export async function verifyProject(projectsDir: string, request: GmVerifyRequest, ledger: ProcessLedger): Promise<GmVerificationResult> {
  if (request.capability !== "GM_VERIFY_V1") fail("GATE_VIOLATION", "verify requires GM_VERIFY_V1"); if (!request.expectedProjectFingerprint) fail("INVALID_REQUEST", "verify requires the current expected fingerprint");
  const levels = [...new Set(request.levels)]; if (!levels.length) fail("INVALID_REQUEST", "verify requires at least one level"); const allowed = new Set<VerificationLevel>(["TEXT_VALID", "PROJECT_LOAD_VALID", "COMPILE_VALID", "RUNTIME_VALID"]); if (levels.some((level) => !allowed.has(level))) fail("INVALID_REQUEST", "unknown verification level");
  if (levels.includes("RUNTIME_VALID") && request.verificationPolicy.runtime === "forbidden") fail("GATE_VIOLATION", "runtime verification is forbidden by policy"); if ((levels.includes("COMPILE_VALID") || levels.includes("RUNTIME_VALID")) && !request.igor) fail("INVALID_REQUEST", "compile/runtime verification requires explicit Igor configuration");
  if (request.plan) { if (!request.planHash || planHash(request.plan) !== request.planHash || request.plan.transactionId !== request.transactionId) fail("PLAN_STALE", "verify plan binding is invalid", true); const manifestPath = await resolveInsideRoot(projectsDir, `${safeRelativePath(request.evidenceRoot)}/transactions/${request.transactionId}/manifest.json`); if (!(await stat(manifestPath).catch(() => null))) fail("MUTATION_NOT_FOUND", "verify requires an applied transaction", true); const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as { planHash?: string; state?: string }; if (manifest.planHash !== request.planHash || manifest.state !== "APPLIED") fail("PLAN_STALE", "verify plan does not match the applied manifest", true); }
  const snapshot = await inspectProject(projectsDir, { ...request, capability: "GM_INSPECT_V1" }, ledger.inventory); const root = await resolveInsideRoot(projectsDir, request.projectRoot, { existing: true });
  if (request.plan) for (const file of request.plan.files) { const current = await readFile(await resolveInsideRoot(root, file.path)); if (sha256(current) !== file.afterSha256) fail("CONCURRENT_MODIFICATION", "project differs from applied plan", true, { path: file.path }); }
  const evidenceRoot = safeRelativePath(request.evidenceRoot); if (evidenceRoot === request.projectRoot || evidenceRoot.startsWith(`${request.projectRoot}/`)) fail("AUTHZ_PROJECT_ROOT", "evidenceRoot must be outside projectRoot"); const evidenceRelative = `${evidenceRoot}/transactions/${request.transactionId}/verification`; const evidence = await resolveInsideRoot(projectsDir, evidenceRelative); await mkdir(evidence, { recursive: true });
  const outcomes: Partial<Record<VerificationLevel, VerificationOutcome>> = {}; let compileExitCode: number | null = null; let runtimeObserved = false; let ownedPids: readonly number[] = Object.freeze([]);
  try { await textVerification(root); outcomes.TEXT_VALID = passed(`${evidenceRelative}/verify.json`, "GameMaker JSON and basic GML structure parsed"); } catch (error) { outcomes.TEXT_VALID = failed(`${evidenceRelative}/verify.json`, error instanceof Error ? error.message : String(error)); }
  if ((levels.includes("PROJECT_LOAD_VALID") || levels.includes("COMPILE_VALID") || levels.includes("RUNTIME_VALID")) && request.igor) {
    ensureToolchain(request.igor); for (const path of [request.igor.executable, request.igor.runtimePath, request.igor.userDirectory, request.igor.projectTool]) if (!(await stat(path).catch(() => null))) fail("INVALID_REQUEST", "Igor toolchain path does not exist", false, { path });
    const foreignRunners = (await ledger.inventory()).filter(({ name }) => /^Runner(?:\.exe)?$/i.test(name)); if (foreignRunners.length) fail("RUN_BLOCKED_EXTERNAL_RUNNER", "foreign Runner exists before compile/run", true, { pids: foreignRunners.map(({ pid }) => pid) });
    const cache = `${evidence}/cache`; const temp = `${evidence}/temp`; const output = `${evidence}/output`; await Promise.all([mkdir(cache, { recursive: true }), mkdir(temp, { recursive: true }), mkdir(output, { recursive: true })]);
    const project = `${root}/${snapshot.projectFile}`; const args = [`--project=${project}`, `--rp=${request.igor.runtimePath}`, `--user=${request.igor.userDirectory}`, `--projectool=${request.igor.projectTool}`, `--runtime=${request.igor.runtime ?? "VM"}`, `--cache=${cache}`, `--temp=${temp}`, "--consoleRedirect", "--", request.igor.worker ?? "windows", "Run"];
    const invocation = { executable: request.igor.executable, version: request.igor.runtimePath.split(/[\\/]/).pop() ?? "unknown", arguments: args, commandHash: commandHash(request.igor.executable, args), timeoutMs: request.timeoutMs, projectFingerprint: snapshot.fingerprint };
    await writeFile(`${evidence}/compile-invocation.json`, canonicalBytes(invocation));
    try {
      const result = await runOwnedCommand({ executable: request.igor.executable, args, cwd: evidence, transactionId: request.transactionId, timeoutMs: request.timeoutMs, cancellation: request.cancellation, ledger, expectedRuntimeSignal: request.expectedRuntimeSignal }); compileExitCode = result.exitCode; ownedPids = result.ownedPids;
      await writeFile(`${evidence}/compile.log`, `${result.stdout}\n--- STDERR ---\n${result.stderr}`, "utf8");
      const recognized = result.stdout.length + result.stderr.length > 0 && !/project.+(?:invalid|not found|failed to load)/i.test(`${result.stdout}\n${result.stderr}`); outcomes.PROJECT_LOAD_VALID = recognized ? passed(`${evidenceRelative}/compile.log`, "Igor accepted and processed the .yyp project") : failed(`${evidenceRelative}/compile.log`, "Igor did not prove project recognition");
      outcomes.COMPILE_VALID = result.exitCode === 0 ? passed(`${evidenceRelative}/compile.log`, "Igor exited 0 after a current invocation") : failed(`${evidenceRelative}/compile.log`, `Igor exited ${result.exitCode}`);
      runtimeObserved = Boolean(request.expectedRuntimeSignal && `${result.stdout}\n${result.stderr}`.includes(request.expectedRuntimeSignal) && result.observedRunners.length > 0);
      outcomes.RUNTIME_VALID = runtimeObserved ? passed(`${evidenceRelative}/compile.log`, "owned Runner emitted the expected signal") : failed(`${evidenceRelative}/compile.log`, "expected runtime signal and owned Runner were not both observed");
      for (const runner of result.observedRunners) if (await ledger.identityMatches(runner)) await ledger.terminateRecord(runner, request.transactionId);
    } catch (error) {
      const details = error instanceof GmAdapterError ? error.details : {}; const stdout = typeof details.stdout === "string" ? details.stdout : ""; const stderr = typeof details.stderr === "string" ? details.stderr : ""; await writeFile(`${evidence}/compile.log`, `${stdout}\n--- STDERR ---\n${stderr}`, "utf8"); await writeFile(`${evidence}/process-ledger.json`, canonicalBytes({ records: ledger.records(request.transactionId), error: error instanceof Error ? error.message : String(error) })); throw error;
    }
  }
  const orderedLevels: readonly VerificationLevel[] = ["TEXT_VALID", "PROJECT_LOAD_VALID", "COMPILE_VALID", "RUNTIME_VALID"]; const requestedOutcomes = Object.fromEntries(levels.map((level) => [level, outcomes[level] ?? failed(`${evidenceRelative}/verify.json`, "level was not executed")])) as Partial<Record<VerificationLevel, VerificationOutcome>>; const highestLevel = [...orderedLevels].reverse().find((level) => requestedOutcomes[level]?.passed) ?? null;
  const rollbackRequired = levels.some((level) => !requestedOutcomes[level]?.passed) && !(levels.includes("RUNTIME_VALID") && request.verificationPolicy.runtime === "optional" && levels.filter((level) => level !== "RUNTIME_VALID").every((level) => requestedOutcomes[level]?.passed));
  const result: GmVerificationResult = Object.freeze({ schemaVersion: 1, transactionId: request.transactionId, levels: Object.freeze(requestedOutcomes), highestLevel, rollbackRequired, compileExitCode, runtimeObserved, ownedPids, evidencePath: `${evidenceRelative}/verify.json` }); await writeFile(`${evidence}/process-ledger.json`, canonicalBytes({ records: ledger.records(request.transactionId) })); await writeFile(`${evidence}/verify.json`, canonicalBytes(result)); return result;
}
