// Builds THAW from nothing using only the DevLab MCP servers.
//
// Nothing here writes a project file directly: every resource is planned by the
// read tier and applied by the write tier, every sprite comes through the
// Aseprite ingest and the asset bridge, and the art itself is generated by an
// Aseprite script. The playable project is an output, not a checked-in asset.
//
//   node examples/thaw/build-thaw.mjs --out H:/GameMaker-Projects [--clean] [--test] [--run]
//
//   --clean rebuild over an existing Thaw: removes the project directory and the
//           write tier's creation ledger for it, and nothing else
//   --test  bake the recorded solutions in and let the game replay itself
//   --run   compile and launch with Igor when the build finishes
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, "../..");

// examples/ is not a workspace package, so the MCP SDK is resolved from a
// package that depends on it rather than from here.
const requireFromPackage = createRequire(join(REPO, "packages/gamemaker-dev-mcp/package.json"));
const sdk = async (subpath) => {
  try {
    return await import(pathToFileURL(requireFromPackage.resolve(subpath)).href);
  } catch (error) {
    throw new Error(`${subpath} not found -- run "pnpm install" from the monorepo root (${error.message})`);
  }
};
const { Client } = await sdk("@modelcontextprotocol/sdk/client/index.js");
const { StdioClientTransport } = await sdk("@modelcontextprotocol/sdk/client/stdio.js");
const PROJECT = "Thaw";
const ROOM_W = 20;
const ROOM_H = 15;
const TILE = 16;
// The tileset strip is four tiles wide, which is also its column count.
const TILESET_COLUMNS = 4;

const flag = (name) => process.argv.includes(`--${name}`);
const option = (name, fallback) => {
  const index = process.argv.indexOf(`--${name}`);
  return index >= 0 ? process.argv[index + 1] : fallback;
};

const ASEPRITE = process.env.DEVLAB_ASEPRITE ?? "C:/Program Files/Aseprite/Aseprite.exe";
const RUNTIME = process.env.DEVLAB_GM_RUNTIME ?? "C:/ProgramData/GameMakerStudio2/Cache/runtimes/runtime-2024.14.3.260";
const PROJECT_TOOL = process.env.DEVLAB_GM_PROJECT_TOOL ?? "H:/GameMaker-LTS2026/packages/gm-tools/project-tool-win-x64/ProjectTool.exe";
const GM_USER = process.env.DEVLAB_GM_USER_DIR ?? "C:/Users/Deposito/AppData/Roaming/GameMakerStudio2/divididoshastalaspelotas_4974629";

const outRoot = resolve(option("out", join(REPO, "output", "thaw")));
const testing = flag("test");
const runId = Math.random().toString(36).slice(2, 10);
const workRoot = join(outRoot, ".thaw-work");
const catalogRoot = join(workRoot, "catalog");
const sourceRoot = join(workRoot, "aseprite");

// Aseprite's --script-param takes the path verbatim, and a Windows backslash
// reads as an escape inside a Lua string.
const posix = (path) => path.split("\\").join("/");
const gml = (name) => readFileSync(join(HERE, "gml", name), "utf8");
const step = (label, detail = "") => console.log(`  ${label.padEnd(30)} ${detail}`);

// ── art ───────────────────────────────────────────────────────────────────────

console.log(`THAW -> ${join(outRoot, PROJECT)}${testing ? "   (test build)" : ""}`);

// The write tier records every project creation in a ledger outside the
// project, so deleting the directory alone is not "start over" -- it looks like
// a half-finished creation and is refused. Rebuilding therefore has to say so.
const projectDir = join(outRoot, PROJECT);
const ledgerDir = join(outRoot, ".devlab-gamemaker-mcp-write", "create-projects");
const ledgers = existsSync(ledgerDir) ? readdirSync(ledgerDir) : [];
if (flag("clean")) {
  if (existsSync(projectDir)) {
    console.log(`clean  removing ${projectDir}`);
    rmSync(projectDir, { recursive: true, force: true });
  }
  // Only the creation ledger: transaction backups and locks are left alone, so
  // a rollback for some other project is never destroyed by a rebuild here.
  for (const entry of ledgers) {
    console.log(`clean  removing creation ledger ${entry}`);
    rmSync(join(ledgerDir, entry), { force: true });
  }
} else if (existsSync(projectDir) || ledgers.length) {
  console.error(`${projectDir} already exists (or has a creation ledger). Pass --clean to rebuild it.`);
  process.exit(1);
}

rmSync(workRoot, { recursive: true, force: true });
mkdirSync(sourceRoot, { recursive: true });
mkdirSync(join(catalogRoot, "assets/catalog"), { recursive: true });
writeFileSync(
  join(catalogRoot, "assets/catalog/asset-catalog.json"),
  `${JSON.stringify({ entries: [], migration: "asset-catalog-v1", schemaVersion: 1 }, null, 2)}\n`,
  "utf8",
);

console.log("art");
const artLog = execFileSync(ASEPRITE, [
  "-b", "--script-param", `outdir=${posix(sourceRoot)}`, "--script", join(HERE, "art/thaw-art.lua"),
], { encoding: "utf8", windowsHide: true, timeout: 120_000 });
step("aseprite", artLog.trim());

// ── servers ───────────────────────────────────────────────────────────────────

const clients = [];
async function connect(pkg, env) {
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [join(REPO, "packages", pkg, "dist/index.js")],
    env: { ...process.env, ...env },
    stderr: "pipe",
  });
  const client = new Client({ name: "thaw-build", version: "1.0.0" });
  await client.connect(transport);
  transport.stderr?.on("data", (chunk) => process.stderr.write(`[${pkg}] ${chunk}`));
  clients.push(client);
  return async (tool, args = {}) => {
    const result = await client.callTool({ name: tool, arguments: args });
    const body = result.structuredContent;
    if (!body) throw new Error(`${tool}: ${JSON.stringify(result.content)}`);
    if (body.ok === false) throw new Error(`${tool} refused: ${body.error.code} -- ${body.error.message}`);
    return body;
  };
}

try {
  mkdirSync(outRoot, { recursive: true });
  const write = await connect("gamemaker-write-mcp", { DEVLAB_GM_PROJECTS_DIR: outRoot, DEVLAB_GM_WRITE_ALLOW: "*" });
  const read = await connect("gamemaker-dev-mcp", { DEVLAB_GM_PROJECTS_DIR: outRoot });
  const ingest = await connect("aseprite-ingest-mcp", {
    DEVLAB_ASEPRITE: ASEPRITE,
    DEVLAB_ASEPRITE_SOURCE_ROOT: sourceRoot,
    DEVLAB_ASEPRITE_REPO_ROOT: catalogRoot,
    DEVLAB_ASEPRITE_WRITE: "1",
  });
  const asset = await connect("gamemaker-asset-mcp", {
    DEVLAB_GM_PROJECTS_DIR: outRoot,
    DEVLAB_GM_ASSET_CATALOG: join(catalogRoot, "assets/catalog/asset-catalog.json"),
    DEVLAB_GM_ASSET_REPO_ROOT: catalogRoot,
    DEVLAB_GM_ASSET_WRITE: "1",
  });

  const fingerprint = async () => (await read("gamemaker_inspect", { projectPath: PROJECT })).fingerprint;

  /** Plans one resource and applies it, so each call leaves the project valid. */
  async function author(tool, args) {
    const plan = await read(tool, { projectPath: PROJECT, expectedProjectFingerprint: await fingerprint(), ...args });
    await write("gamemaker_apply", {
      projectPath: PROJECT, plan: plan.plan, planHash: plan.planHash, confirm: true, dryRun: false,
    });
    return plan;
  }

  async function importSprite(assetId, resourceName, file, origin) {
    await ingest("aseprite_ingest", { source: file, assetId, version: "1.0.0", origin });
    await ingest("aseprite_publish", { assetId, version: "1.0.0", status: "APPROVED", confirm: true, dryRun: false });
    const transactionId = `thaw-${assetId}-${runId}`;
    const before = await fingerprint();
    const plan = await asset("asset_plan_import", {
      projectPath: PROJECT, expectedProjectFingerprint: before,
      assetId, assetVersion: "1.0.0", resourceName, transactionId,
    });
    await asset("asset_apply_import", {
      projectPath: PROJECT, expectedProjectFingerprint: before,
      assetId, assetVersion: "1.0.0", resourceName, transactionId,
      planHash: plan.planHash, bindingHash: plan.bindingHash, confirm: true, dryRun: false,
    });
    step(resourceName, `from ${assetId}`);
  }

  console.log("project");
  await write("gamemaker_create_project", { projectPath: PROJECT, name: PROJECT, confirm: true, dryRun: false });
  step("gamemaker_create_project", `${PROJECT}.yyp`);

  console.log("sprites");
  // The tileset source is one strip, so its origin is irrelevant; the actors are
  // drawn from their centre because the game positions them by cell centre.
  await importSprite("thaw-tiles", "spr_tiles", "ts_thaw.aseprite", "top-left");
  await importSprite("thaw-hero", "spr_hero", "spr_hero.aseprite", "centre");
  await importSprite("thaw-block", "spr_block", "spr_block.aseprite", "centre");

  console.log("resources");
  const tileset = await author("gamemaker_plan_new_tileset", {
    name: "ts_thaw", spriteName: "spr_tiles", tileWidth: TILE, tileHeight: TILE,
  });
  step("ts_thaw", tileset.resourcePath);

  // A GMTileSet record alone renders nothing. GameMaker also wants
  // `output_tileset.png` beside it: every tile re-laid-out into a
  // (tile + 2*border) cell with its edges bled outward. tilemap_get returns the
  // right indices without it, which is why authoring the record looked complete
  // until a frame of the running game was actually looked at.
  // gamemaker_plan_new_tileset does not emit it yet, so it is generated here.
  const tilesetDir = join(outRoot, PROJECT, "tilesets", "ts_thaw");
  const pageLog = execFileSync(ASEPRITE, [
    "-b",
    "--script-param", `src=${posix(join(outRoot, PROJECT, "sprites/spr_tiles/0.png"))}`,
    "--script-param", `out=${posix(join(tilesetDir, "output_tileset.png"))}`,
    "--script-param", `tile=${TILE}`,
    "--script-param", "border=2",
    "--script-param", `columns=${TILESET_COLUMNS}`,
    "--script", join(HERE, "art/tileset-page.lua"),
  ], { encoding: "utf8", windowsHide: true, timeout: 120_000 });
  step("output_tileset.png", pageLog.trim());

  await author("gamemaker_plan_new_script", { name: "scr_thaw", gml: gml("scr_thaw.gml") });
  step("scr_thaw", "rules, levels and solutions");

  await author("gamemaker_plan_new_script", {
    name: "scr_thaw_testing",
    gml: `// Written by build-thaw.mjs. --test bakes the recorded solutions in.\nfunction thaw_testing() {\n  return ${testing};\n}\n`,
  });
  step("scr_thaw_testing", `thaw_testing() -> ${testing}`);

  await author("gamemaker_plan_new_object", {
    name: "obj_hero", spriteName: "spr_hero",
    events: [
      { event: "create", gml: gml("obj_hero_create.gml") },
      { event: "step", gml: gml("obj_hero_step.gml") },
    ],
  });
  step("obj_hero", "spr_hero");

  await author("gamemaker_plan_new_object", {
    name: "obj_block", spriteName: "spr_block",
    events: [
      { event: "create", gml: gml("obj_block_create.gml") },
      { event: "step", gml: gml("obj_block_step.gml") },
      { event: "draw", gml: gml("obj_block_draw.gml") },
    ],
  });
  step("obj_block", "spr_block");

  await author("gamemaker_plan_new_object", {
    name: "obj_game",
    events: [
      { event: "create", gml: gml("obj_game_create.gml") },
      { event: "step", gml: gml("obj_game_step.gml") },
      { event: "draw", eventNum: 64, gml: gml("obj_game_drawgui.gml") },
    ],
  });
  step("obj_game", "controller, HUD");

  await author("gamemaker_plan_new_room", {
    name: "rm_thaw",
    width: ROOM_W * TILE,
    height: ROOM_H * TILE,
    instances: [{ objectName: "obj_game", x: 0, y: 0 }],
  });
  step("rm_thaw", `${ROOM_W * TILE}x${ROOM_H * TILE}`);

  // The layer is authored empty and painted at run time, so one room serves
  // every level instead of one room per level.
  await author("gamemaker_plan_tile_layer", {
    roomName: "rm_thaw", layerName: "Tiles_level", tilesetName: "ts_thaw",
    width: ROOM_W, height: ROOM_H,
    cells: new Array(ROOM_W * ROOM_H).fill(-2147483648),
    depth: 100,
  });
  step("Tiles_level", `${ROOM_W}x${ROOM_H}, painted at run time`);

  const final = await read("gamemaker_inspect", { projectPath: PROJECT });
  console.log(`\nbuilt: ${final.fileCount} files, fingerprint ${final.fingerprint.slice(0, 12)}...`);
} finally {
  for (const client of clients) await client.close().catch(() => {});
}

// ── compile ───────────────────────────────────────────────────────────────────

if (flag("run")) {
  console.log("\nigor");
  const cache = join(workRoot, "cache");
  const temp = join(workRoot, "temp");
  mkdirSync(cache, { recursive: true });
  mkdirSync(temp, { recursive: true });
  let out = "";
  let code = 0;
  try {
    out = execFileSync(`${RUNTIME}/bin/igor/windows/x64/Igor.exe`, [
      `--project=${join(outRoot, PROJECT, `${PROJECT}.yyp`)}`,
      `--rp=${RUNTIME}`, `--user=${GM_USER}`, `--projectool=${PROJECT_TOOL}`,
      "--runtime=VM", `--cache=${cache}`, `--temp=${temp}`, "--consoleRedirect",
      "--", "windows", "Run",
    ], { encoding: "utf8", timeout: 600_000, windowsHide: true, maxBuffer: 64 * 1024 * 1024 });
  } catch (error) {
    out = `${error.stdout ?? ""}\n${error.stderr ?? ""}`;
    code = error.status ?? -1;
  }
  for (const line of out.split(/\r?\n/)) {
    if (/^\s*Error\s*:|THAW |Cannot find|Failed to/.test(line)) console.log(`  ${line.trim()}`);
  }
  console.log(`\nigor exit: ${code}`);
  if (testing) {
    const solved = (out.match(/THAW SOLVED/g) ?? []).length;
    const all = /THAW ALL SOLVED/.test(out);
    const failed = /THAW FAILED/.test(out);
    console.log(`replay: ${solved} level(s) solved, all=${all}, failed=${failed}`);
    if (!all || failed) process.exitCode = 1;
  } else if (code !== 0) {
    process.exitCode = 1;
  }
}
