import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import { GovernedAssetGmBridge, createBridgeTestBeacon, encodePng, insertIntoGmArray, parseGmJson } from "../dist/index.js";
import { SPEC_V1, baseRequest, makeWorkspace } from "./helpers.js";

test("PNG encoding is byte-deterministic across calls", () => {
  const first = createBridgeTestBeacon(SPEC_V1);
  const second = createBridgeTestBeacon(SPEC_V1);
  for (let i = 0; i < first.pngBytes.length; i += 1) {
    assert.ok(first.pngBytes[i].equals(second.pngBytes[i]), `frame ${i} differs`);
    assert.equal(first.frames[i].sha256, second.frames[i].sha256);
  }
  assert.equal(first.pixelSignature.sha256, second.pixelSignature.sha256);
});

test("encodePng round-trips through parsePng with identical pixels", async () => {
  const { parsePng } = await import("../../img2threejs-asset-forge/dist/index.js");
  const asset = createBridgeTestBeacon(SPEC_V1);
  const parsed = parsePng(asset.pngBytes[1]);
  assert.equal(parsed.width, 64);
  assert.equal(parsed.height, 64);
  assert.equal(parsed.channels, 4);
  assert.deepEqual(Buffer.from(parsed.pixels), Buffer.from(asset.frames[1].rgba));
});

test("v1 and v2 beacons are visually distinct (different pixels and signatures)", () => {
  const v1 = createBridgeTestBeacon(SPEC_V1);
  const v2 = createBridgeTestBeacon({ ...SPEC_V1, version: "2.0.0", palette: "v2-magenta" });
  assert.notEqual(v1.pixelSignature.sha256, v2.pixelSignature.sha256);
  let differences = 0;
  for (let i = 0; i < v1.frames[1].rgba.length; i += 1) if (v1.frames[1].rgba[i] !== v2.frames[1].rgba[i]) differences += 1;
  assert.ok(differences > 100, "v1 and v2 must differ in many pixels");
});

test("identical inputs across workspaces produce identical plans (byte determinism)", async () => {
  const results = [];
  for (let run = 0; run < 2; run += 1) {
    const workspace = makeWorkspace({});
    const bridge = new GovernedAssetGmBridge(workspace.projectsDir, { catalogPath: workspace.catalogPath, repoRoot: workspace.root });
    const target = await bridge.inspectTarget(baseRequest(workspace));
    const request = { ...baseRequest(workspace), expectedProjectFingerprint: target.fingerprint };
    results.push(await bridge.planImport(request));
  }
  const [first, second] = results;
  assert.equal(first.bindingHash, second.bindingHash);
  assert.equal(first.manifestHash, second.manifestHash);
  assert.equal(first.planHash, second.planHash);
  assert.deepEqual(first.files, second.files);
  assert.deepEqual(first.manifest, second.manifest);
});

test("the .yyp patch is a minimal splice that preserves every other byte", async () => {
  const workspace = makeWorkspace({});
  const bridge = new GovernedAssetGmBridge(workspace.projectsDir, { catalogPath: workspace.catalogPath, repoRoot: workspace.root });
  const target = await bridge.inspectTarget(baseRequest(workspace));
  const request = { ...baseRequest(workspace), expectedProjectFingerprint: target.fingerprint };
  const plan = await bridge.planImport(request);
  const before = readFileSync(join(workspace.projectsDir, "pilot-a/AssetBridgePilot.yyp"), "utf8");
  const applied = await bridge.applyImport({ ...request, plan: plan.plan, planHash: plan.planHash, bindingHash: plan.bindingHash, confirm: true, dryRun: false });
  assert.equal(applied.state, "APPLIED");
  const after = readFileSync(join(workspace.projectsDir, "pilot-a/AssetBridgePilot.yyp"), "utf8");
  // The only difference is the added resources line; the rest is byte-identical.
  const addedLine = '    {"id":{"name":"spr_bridge_test_beacon","path":"sprites/spr_bridge_test_beacon/spr_bridge_test_beacon.yy",},},\n';
  assert.ok(after.includes(addedLine));
  assert.equal(after.replace(addedLine, ""), before);
});

test("no UUIDs are generated by the import (stable identity by name/path)", async () => {
  const workspace = makeWorkspace({});
  const bridge = new GovernedAssetGmBridge(workspace.projectsDir, { catalogPath: workspace.catalogPath, repoRoot: workspace.root });
  const target = await bridge.inspectTarget(baseRequest(workspace));
  const request = { ...baseRequest(workspace), expectedProjectFingerprint: target.fingerprint };
  const plan = await bridge.planImport(request);
  const applied = await bridge.applyImport({ ...request, plan: plan.plan, planHash: plan.planHash, bindingHash: plan.bindingHash, confirm: true, dryRun: false });
  assert.equal(applied.state, "APPLIED");
  const yy = readFileSync(join(workspace.projectsDir, "pilot-a/sprites/spr_bridge_test_beacon/spr_bridge_test_beacon.yy"), "utf8");
  const uuidPattern = /[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}/i;
  assert.ok(!uuidPattern.test(yy), "sprite .yy must not contain UUIDs");
  assert.ok(!readFileSync(join(workspace.projectsDir, "pilot-a/AssetBridgePilot.yyp"), "utf8").match(uuidPattern));
});

test("insertIntoGmArray gives the first entry of an empty array no leading comma", () => {
  // A project created from nothing has empty arrays, so importing the first
  // sprite into one hit this. Emitting a separator produced `[,`, which
  // GameMaker refuses to load.
  const empties = ['{"resources":[]}', '{"resources":[\n  ]}', '{"resources":[\n\n]}'];
  for (const empty of empties) {
    const patched = insertIntoGmArray(empty, '"resources":[', "a/a.yy", '{"id":{"name":"a","path":"a/a.yy",},}');
    assert.ok(!/\[\s*,/.test(patched), `leading comma in ${JSON.stringify(patched)}`);
    const parsed = parseGmJson(patched);
    assert.equal(parsed.resources.length, 1);
    assert.equal(parsed.resources[0].id.name, "a");
  }
});

test("insertIntoGmArray is not fooled by a nested empty array", () => {
  const nested = '{"resources":[\n    {"id":{"name":"a","path":"a/a.yy",},"tags":[],},\n  ]}';
  const patched = insertIntoGmArray(nested, '"resources":[', "b/b.yy", '{"id":{"name":"b","path":"b/b.yy",},}');
  const parsed = parseGmJson(patched);
  assert.equal(parsed.resources.length, 2);
  assert.deepEqual(parsed.resources.map((r) => r.id.name), ["a", "b"]);
});

test("insertIntoGmArray keeps hand-authored (non-comma-terminated) arrays parseable", () => {
  // Hand-authored GM text may omit the element-separating comma on the last
  // element. The patcher must add the separator so the patched file parses.
  const text = '{\n  "resources":[\n    {"id":{"name":"a","path":"a/a.yy",},}\n  ],\n}';
  const patched = insertIntoGmArray(text, '"resources":[', "b/b.yy", '{"id":{"name":"b","path":"b/b.yy",},}');
  const parsed = parseGmJson(patched);
  assert.equal(parsed.resources.length, 2);
  assert.equal(parsed.resources[1].id.name, "b");
  // A second call is idempotent.
  const again = insertIntoGmArray(patched, '"resources":[', "b/b.yy", '{"id":{"name":"b","path":"b/b.yy",},}');
  assert.equal(again, patched);
});
